### ISSUE TITLE
Bootloop on macOS 14 Sonoma

### ISSUE THREAD

**Issue by frost-1256** [ChefKissInc/NootedRed#194]
**Describe the bug**
On macOS 14 Sonoma,the login screen is a bit choppy, etc., and the system reboots a few seconds after logging in.
With Ventura and Sonoma Beta, there was no problem.

**To Reproduce**
Booting with NootedRed enabled in Sonoma

**Expected behavior**

**Screenshots**

**System Information:**
 - macOS Version: macOS 14 Sonoma 14.1 23B74
 - CPU: Ryzen 3 3200G

**Additional context**
4GB of memory was configured from UEFI.

**Comment by frost-1256** [comment]
I am currently testing again and it reboots with the Apple logo after the verbose log!

**Comment by frost-1256** [comment]
When I waited a bit and logged in, a panic repair boot
message appeared and rebooted after a few seconds
![IMG_3525(1)](https://github.com/ChefKissInc/NootedRed/assets/108122312/578cb59a-ac07-4941-9329-8e38b478a8c4)

**Comment by pmnlla** [comment]
Managed to recreate. Will upload logs later. 
For future reference, what version of NRed are you running?

**Comment by ethernetme** [comment]
My kexts are updated, but I'm still getting this issue

**Comment by VisualEhrmanntraut** [comment]
send your config with the serials stripped

**Comment by VisualEhrmanntraut** [comment]
> the login screen is a bit choppy

Probably TSC sync issue

**Comment by ethernetme** [comment]
> send your config with the serials stripped

Here it is. If you find a fix, I wouldn't be able to test it though, since I'm already reinstalling Ventura. I didn't get the issue on that OS, only after updating to Sonoma.

[config.zip](https://github.com/ChefKissInc/NootedRed/files/13325823/config.zip)

**Comment by VisualEhrmanntraut** [comment]
> Probably TSC sync issue

Ditto.

**Comment by VisualEhrmanntraut** [comment]
Closing due to unwillingness to resolve issue.

**Comment by pmnlla** [comment]
So what should i do to solve the issue?

**Comment by VisualEhrmanntraut** [comment]
Configure your system properly.

**Comment by ethernetme** [comment]
what do you think we've doing hun

**Comment by VisualEhrmanntraut** [comment]
Not that. :-) I suggest you retry with the commit I pushed a bit ago.

**Comment by pmnlla** [comment]
> Configure your system properly.

Yes I'm well aware there's a potential issue with our configs. I looked up TSC sync in Dortania's guides and only found an ssdt that works for Intel cpus. What do you want me to try?

**Comment by pmnlla** [comment]
Seeking an update on this. AmdTscSync did not fix the issue.

**Comment by pmnlla** [comment]
Seeking an update on this again. Tried adding AmdTscSync to my kexts, that did not fix it.

**Comment by ethernetme** [comment]
> Not that. :-) I suggest you retry with the commit I pushed a bit ago.

Weeks later, I'm still getting this issue in Sonoma even with a clean install and the latest version of the kext. The installation went through just fine but it keeps bootlooping on the first boot screen. Would you mind helping me find the issue? Here is my config file if needed:
[config.zip](https://github.com/ChefKissInc/NootedRed/files/13787842/config.zip)
